version: '3.8'

services:
  apiservice:
    image: ghcr.io/dariovlahovic/testingalphadeploy/apiservice:latest
    ports:
      - "8080:8080"
      - "8081:8081"
    restart: unless-stopped

  web:
    image: ghcr.io/dariovlahovic/testingalphadeploy/web:latest
    ports:
      - "8082:8080"
      - "8083:8081"
    restart: unless-stopped
    depends_on:
      - apiservice