name: Merge master to publish

on:
  push:
    branches:
      - master

jobs:
  merge:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Merge master to publish
      uses: devmasx/merge-branch@1.4.0
      with:
        type: now
        from_branch: master
        target_branch: publish
        github_token: ${{ secrets.GITHUB_TOKEN }}